M48
; DRILL file {KiCad 7.0.9} date Wed May 22 12:08:39 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-22T12:08:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.2362
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.3307
%
G90
G05
T1
X2.0866Y-2.0866
X2.0866Y-5.7874
X3.8189Y-2.0866
X3.8189Y-5.7874
T2
X2.9528Y-3.937
T3
X2.9528Y-2.5591
T0
M30
